2025-04-17 20:37:35.970 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-17 20:37:35.972 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-17 20:37:35.999 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-17 20:37:36.000 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-17 20:37:36.006 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-17 20:37:36.007 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-17 21:11:32.686 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-17 21:11:32.687 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-17 21:11:32.786 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-17 21:11:32.787 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-17 21:11:32.793 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-17 21:11:32.794 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-17 21:14:22.130 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-17 21:14:22.130 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-17 21:14:22.171 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-17 21:14:22.171 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-17 21:14:22.175 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-17 21:14:22.175 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-17 21:15:08.217 | 199b777313ab4ddba49e7cf58527e81a | ERROR    | exceptions.handle:exception_handler:53 - BaseModel.__init__() takes 1 positional argument but 2 were given
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "/disc/home/beng003/.local/share/uv/python/cpython-3.10.16-linux-x86_64-gnu/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               │     │   └ 4
               │     └ 13
               └ <function _main at 0x7110057132e0>
  File "/disc/home/beng003/.local/share/uv/python/cpython-3.10.16-linux-x86_64-gnu/lib/python3.10/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
           │    │          └ 4
           │    └ <function BaseProcess._bootstrap at 0x71100585a320>
           └ <SpawnProcess name='SpawnProcess-1' parent=75171 started>
  File "/disc/home/beng003/.local/share/uv/python/cpython-3.10.16-linux-x86_64-gnu/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x711005859990>
    └ <SpawnProcess name='SpawnProcess-1' parent=75171 started>
  File "/disc/home/beng003/.local/share/uv/python/cpython-3.10.16-linux-x86_64-gnu/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {'config': <uvicorn.config.Config object at 0x7110057173a0>, 'target': <bound method Server.run of <uvicorn.server.Server obj...
    │    │        │    │        └ <SpawnProcess name='SpawnProcess-1' parent=75171 started>
    │    │        │    └ ()
    │    │        └ <SpawnProcess name='SpawnProcess-1' parent=75171 started>
    │    └ <function subprocess_started at 0x7110051a7b50>
    └ <SpawnProcess name='SpawnProcess-1' parent=75171 started>
  File "/disc/home/beng003/work/DAGScheduler​/.venv/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
    │              └ [<socket.socket fd=9, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 9099)>]
    └ <bound method Server.run of <uvicorn.server.Server object at 0x7110057174c0>>
  File "/disc/home/beng003/work/DAGScheduler​/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ [<socket.socket fd=9, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 9099)>]
           │       │   │    └ <function Server.serve at 0x7110051a6ef0>
           │       │   └ <uvicorn.server.Server object at 0x7110057174c0>
           │       └ <function run at 0x71100572e4d0>
           └ <module 'asyncio' from '/disc/home/beng003/.local/share/uv/python/cpython-3.10.16-linux-x86_64-gnu/lib/python3.10/asyncio/__i...
  File "/disc/home/beng003/.local/share/uv/python/cpython-3.10.16-linux-x86_64-gnu/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7110010195b0>
           │    └ <cyfunction Loop.run_until_complete at 0x71100104c6c0>
           └ <uvloop.Loop running=True closed=False debug=False>
  File "/disc/home/beng003/work/DAGScheduler​/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
                   └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x71100101fb50>
  File "/disc/home/beng003/work/DAGScheduler​/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
                 │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7110010eb7...
                 │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7110010...
                 │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 9099), 'cl...
                 │    └ <fastapi.applications.FastAPI object at 0x711005717790>
                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x71100101fb50>
  File "/disc/home/beng003/work/DAGScheduler​/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7110010eb7...
                           │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7110010...
                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 9099), 'cl...
  File "/disc/home/beng003/work/DAGScheduler​/.venv/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7110010eb7...
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7110010...
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 9099), 'cl...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7110010e9f30>
          └ <fastapi.applications.FastAPI object at 0x711005717790>
> File "/disc/home/beng003/work/DAGScheduler​/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x711003edb010>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7110010...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 9099), 'cl...
          │    └ <middlewares.trace_middleware.middle.TraceASGIMiddleware object at 0x7110010e9fc0>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7110010e9f30>

  File "/disc/home/beng003/work/DAGScheduler​/middlewares/trace_middleware/middle.py", line 62, in __call__
    await self.app(scope, handle_outgoing_receive, handle_outgoing_request)
          │    │   │      │                        └ <function TraceASGIMiddleware.__call__.<locals>.handle_outgoing_request at 0x711003edb130>
          │    │   │      └ <function RequestResponseCycle.receive at 0x711003edb1c0>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 9099), 'cl...
          │    └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x7110010e9ff0>
          └ <middlewares.trace_middleware.middle.TraceASGIMiddleware object at 0x7110010e9fc0>

  File "/disc/home/beng003/work/DAGScheduler​/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
          │                            │    │    │     │      │        └ <function TraceASGIMiddleware.__call__.<locals>.handle_outgoing_request at 0x711003edb130>
          │                            │    │    │     │      └ <function RequestResponseCycle.receive at 0x711003edb1c0>
          │                            │    │    │     └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 9099), 'cl...
          │                            │    │    └ <starlette.requests.Request object at 0x7110010eb910>
          │                            │    └ <fastapi.routing.APIRouter object at 0x7110011d5750>
          │                            └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x7110010e9ff0>
          └ <function wrap_app_handling_exceptions at 0x7110045f6200>
  File "/disc/home/beng003/work/DAGScheduler​/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/disc/home/beng003/work/DAGScheduler​/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x711003edb250>
          │   │      └ <function RequestResponseCycle.receive at 0x711003edb1c0>
          │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 9099), 'cl...
          └ <fastapi.routing.APIRouter object at 0x7110011d5750>
  File "/disc/home/beng003/work/DAGScheduler​/.venv/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x711003edb250>
          │    │                │      └ <function RequestResponseCycle.receive at 0x711003edb1c0>
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 9099), 'cl...
          │    └ <bound method Router.app of <fastapi.routing.APIRouter object at 0x7110011d5750>>
          └ <fastapi.routing.APIRouter object at 0x7110011d5750>
  File "/disc/home/beng003/work/DAGScheduler​/.venv/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x711003edb250>
          │     │      │      └ <function RequestResponseCycle.receive at 0x711003edb1c0>
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 9099), 'cl...
          │     └ <function Route.handle at 0x7110045f76d0>
          └ APIRoute(path='/monitor/task/{task_uid}', name='query_detail_system_task', methods=['GET'])
  File "/disc/home/beng003/work/DAGScheduler​/.venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x711003edb250>
          │    │   │      └ <function RequestResponseCycle.receive at 0x711003edb1c0>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 9099), 'cl...
          │    └ <function request_response.<locals>.app at 0x7110011e9e10>
          └ APIRoute(path='/monitor/task/{task_uid}', name='query_detail_system_task', methods=['GET'])
  File "/disc/home/beng003/work/DAGScheduler​/.venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
          │                            │    │        │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x711003edb250>
          │                            │    │        │      └ <function RequestResponseCycle.receive at 0x711003edb1c0>
          │                            │    │        └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 9099), 'cl...
          │                            │    └ <starlette.requests.Request object at 0x7110010eba90>
          │                            └ <function request_response.<locals>.app.<locals>.app at 0x711003edb2e0>
          └ <function wrap_app_handling_exceptions at 0x7110045f6200>
  File "/disc/home/beng003/work/DAGScheduler​/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/disc/home/beng003/work/DAGScheduler​/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x711003edb370>
          │   │      └ <function RequestResponseCycle.receive at 0x711003edb1c0>
          │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 9099), 'cl...
          └ <function request_response.<locals>.app.<locals>.app at 0x711003edb2e0>
  File "/disc/home/beng003/work/DAGScheduler​/.venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
                     │ └ <starlette.requests.Request object at 0x7110010eba90>
                     └ <function get_request_handler.<locals>.app at 0x7110011e9a20>
  File "/disc/home/beng003/work/DAGScheduler​/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                         └ <function run_endpoint_function at 0x711004421240>
  File "/disc/home/beng003/work/DAGScheduler​/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
                 │         │      └ {'query_db': <sqlalchemy.ext.asyncio.session.AsyncSession object at 0x7110010ebe50>, 'task_uid': 'task_no_dependencies', 'req...
                 │         └ <function query_detail_system_task at 0x711001504700>
                 └ Dependant(path_params=[ModelField(field_info=Path(PydanticUndefined), name='task_uid', mode='validation')], query_params=[], ...

  File "/disc/home/beng003/work/DAGScheduler​/module_admin/controller/task_controller.py", line 23, in query_detail_system_task
    task_detail_result = await TaskService.task_detail_services_by_uid(
                               │           └ <classmethod(<function TaskService.task_detail_services_by_uid at 0x7110011e9360>)>
                               └ <class 'module_admin.service.task_service.TaskService'>

  File "/disc/home/beng003/work/DAGScheduler​/module_admin/service/task_service.py", line 230, in task_detail_services_by_uid
    result = TaskModel(task)
             │         └ <module_admin.entity.do.task_do.SysTask object at 0x711003f3cd90>
             └ <class 'module_admin.entity.vo.task_vo.TaskModel'>

TypeError: BaseModel.__init__() takes 1 positional argument but 2 were given
2025-04-17 21:20:10.112 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-17 21:20:10.112 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-17 21:20:10.150 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-17 21:20:10.151 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-17 21:20:10.156 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-17 21:20:10.156 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-17 21:20:15.645 | 9ecddc7a7512432aa4ba8f826293a66a | INFO     | module_admin.controller.task_controller:query_detail_system_task:26 - 获取task_uid为task_no_dependencies的信息成功
2025-04-17 21:44:01.038 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-17 21:44:01.040 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-17 21:44:01.069 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-17 21:44:01.069 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-17 21:44:01.122 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-17 21:44:01.123 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-17 21:44:38.870 | 0ede477b0d034fdab803a6fc90c6c919 | INFO     | module_admin.controller.task_controller:query_detail_system_task:26 - 获取task_uid为task_no_dependencies的信息成功
2025-04-17 21:46:09.105 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-17 21:46:09.107 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-17 21:46:09.144 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-17 21:46:09.145 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-17 21:46:09.193 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-17 21:46:09.194 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-17 21:46:13.420 | 5d9bddf4176942a8973a875f3ff882b0 | INFO     | module_admin.controller.task_controller:query_detail_system_task:26 - 获取task_uid为task_no_dependencies的信息成功
